apiVersion: v1
kind: ConfigMap
metadata:
  name: tcc-config
  namespace: prometheus
data:
  application.properties: |
    # Configurações da aplicação
    management.endpoints.web.exposure.include=*
    management.endpoint.prometheus.enabled=true
    management.metrics.export.prometheus.enabled=true
    logging.level.org.springframework.boot.actuate=DEBUG
    logging.level.io.micrometer=DEBUG
    logging.level.org.springframework.web=DEBUG
    logging.level.org.springframework=DEBUG
