apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcc-deployment
  labels:
    app: tcc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tcc
  template:
    metadata:
      labels:
        app: tcc
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - tcc-maria-k8s-node-1
                - tcc-maria-k8s-node-2
                - tcc-maria-k8s-node-3
      containers:
      - name: tcc-container
        image: soaresmaric/tcc:v5
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "1000m"
            memory: "1Gi"
          limits:
            cpu: "2000m"
            memory: "2Gi"
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:h2:mem:testdb
        - name: SPRING_DATASOURCE_USERNAME
          value: sa
        - name: SPRING_DATASOURCE_PASSWORD
          value: password
