apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcc-deployment
  labels:
    app: tcc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tcc
  template:
    metadata:
      labels:
        app: tcc
    spec:
      containers:
      - name: tcc-container
        image: soaresmaric/tcc:v5
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:h2:mem:testdb
        - name: SPRING_DATASOURCE_USERNAME
          value: sa
        - name: SPRING_DATASOURCE_PASSWORD
          value: password
