apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tcc-servicemonitor
  labels:
    app: tcc
spec:
  selector:
    matchLabels:
      app: tcc
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: 15s
